# Generated by Django 2.2.5 on 2022-08-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220815_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='сreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='сreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='houserule',
            old_name='сreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='сreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='сreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='сreated',
            new_name='created',
        ),
    ]
